name: Using Actions

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-Actions/react-app
        
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
      - name: Install Dependencies
        run: npm ci
        # working-directory: 04-using-Actions/react-app
      
      - name: Run Unit tests
        run: npm run test
        # working-directory: 04-using-Actions/react-app
    #0.checkout the code the repository
    #1.install deps of our react application
    #2.execute automated tests
