name: Sample-App

on: push

jobs:
  echo-hello:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        run: echo "This is for testing"

  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Say Goodbye
        run: echo "This is the second step"
