name: Workflow Runner

on: workflow_dispatch

jobs:
  ubuntu-os:
    runs-on: ubuntu-latest # Using the latest Ubuntu runner
    steps:
      - name: "This job is running on Ubuntu server"
        run: |
          echo "This is running on Ubuntu server"
          echo "Runner OS is $RUNNER_OS"

  windows-os:
    runs-on: windows-latest # Using the latest Windows runner
    steps:
      - name: "This job is running on Windows server"
        shell: bash
        run: |
          echo "This is running on Windows server"
          echo "Runner OS is $RUNNER_OS"
